project:
  type: website
  output-dir: docs

website:
  title: "Pelham Lab's Screener Creation Tools"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - metadata-download.qmd
      - documentation.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true







